"""Stable setting key constants used across the application."""

from enum import StrEnum


class SettingKey(StrEnum):
    """Canonical keys for seeded business settings."""

    COMPANY_NAME = "company_name"
    COMPANY_PHONE = "company_phone"
    COMPANY_ADDRESS = "company_address"
    COMPANY_LOGO = "company_logo"
    CURRENCY = "currency"
    MAXIMUM_INITIAL_PAYMENT_PERCENTAGE = "maximum_initial_payment_percentage"
    MANDATORY_PROCESSING_DAYS = "mandatory_processing_days"
    OPTIONAL_PROCESSING_DAYS = "optional_processing_days"
    INVENTORY_BARCODE_PREFIX = "inventory.barcode.prefix"
    INVENTORY_BARCODE_SEPARATOR = "inventory.barcode.separator"
    INVENTORY_BARCODE_PADDING = "inventory.barcode.padding"
    CUSTOMERS_NUMBER_PREFIX = "customers.number.prefix"
    CUSTOMERS_NUMBER_SEPARATOR = "customers.number.separator"
    CUSTOMERS_NUMBER_PADDING = "customers.number.padding"
    RESERVATIONS_NUMBER_PREFIX = "reservations.number.prefix"
    RESERVATIONS_NUMBER_SEPARATOR = "reservations.number.separator"
    RESERVATIONS_NUMBER_PADDING = "reservations.number.padding"
    RENTALS_NUMBER_PREFIX = "rentals.number.prefix"
    RENTALS_NUMBER_SEPARATOR = "rentals.number.separator"
    RENTALS_NUMBER_PADDING = "rentals.number.padding"
    RETURNS_NUMBER_PREFIX = "returns.number.prefix"
    RETURNS_NUMBER_SEPARATOR = "returns.number.separator"
    RETURNS_NUMBER_PADDING = "returns.number.padding"
    INSPECTION_NUMBER_PREFIX = "inspection.number.prefix"
    INSPECTION_NUMBER_SEPARATOR = "inspection.number.separator"
    INSPECTION_NUMBER_PADDING = "inspection.number.padding"
    PROCESSING_NUMBER_PREFIX = "processing.number.prefix"
    PROCESSING_NUMBER_SEPARATOR = "processing.number.separator"
    PROCESSING_NUMBER_PADDING = "processing.number.padding"
    SETTLEMENT_NUMBER_PREFIX = "settlement.number.prefix"
    SETTLEMENT_NUMBER_SEPARATOR = "settlement.number.separator"
    SETTLEMENT_NUMBER_PADDING = "settlement.number.padding"
    SALE_NUMBER_PREFIX = "sale.number.prefix"
    SALE_NUMBER_SEPARATOR = "sale.number.separator"
    SALE_NUMBER_PADDING = "sale.number.padding"
    ALLOW_MANUAL_SALE_PRICE_OVERRIDE = "allow_manual_sale_price_override"
    ALLOW_MANUAL_RENTAL_PRICE_OVERRIDE = "allow_manual_rental_price_override"
    RESERVATION_CONFLICT_COMPENSATION_ENABLED = "reservation_conflict_compensation_enabled"
    DEFAULT_TIMEZONE = "default_timezone"
    # Identity / security (seeded by identity migration)
    MAX_FAILED_LOGIN_ATTEMPTS = "max_failed_login_attempts"
    ACCOUNT_LOCK_DURATION_MINUTES = "account_lock_duration_minutes"
    PASSWORD_MIN_LENGTH = "password_min_length"
    PASSWORD_REQUIRE_COMPLEXITY = "password_require_complexity"
    PASSWORD_HISTORY_COUNT = "password_history_count"
    PASSWORD_EXPIRE_DAYS = "password_expire_days"
    ACCESS_TOKEN_EXPIRE_MINUTES = "access_token_expire_minutes"
    REFRESH_TOKEN_EXPIRE_DAYS = "refresh_token_expire_days"
    REMEMBER_ME_REFRESH_TOKEN_EXPIRE_DAYS = "remember_me_refresh_token_expire_days"
    # Media storage (seeded by media migration)
    MEDIA_STORAGE_PROVIDER = "media_storage_provider"
    MEDIA_STORAGE_ROOT = "media_storage_root"
    MEDIA_MAX_UPLOAD_BYTES = "media_max_upload_bytes"
    MEDIA_ALLOWED_EXTENSIONS = "media_allowed_extensions"
    MEDIA_ALLOWED_MIME_TYPES = "media_allowed_mime_types"
    # Backup engine (seeded by system backups migration)
    BACKUP_STORAGE_ROOT = "backup.storage_root"
    BACKUP_INCLUDE_MEDIA_DEFAULT = "backup.include_media_default"
