export { AppShellFrame, type AppShellProps } from './app-shell'
export { Sidebar, type SidebarProps } from './sidebar'
export { TopBar, type TopBarProps } from './top-bar'
export { Workspace, type WorkspaceProps } from './workspace'
export { StatusBar, type StatusBarProps } from './status-bar'
export { NavigationSection, type NavigationSectionProps } from './navigation-section'
export { NavigationItem, type NavigationItemProps } from './navigation-item'
export { UserMenu, type UserMenuProps } from './user-menu'
export { AboutDialog, type AboutDialogProps } from './about-dialog'
export { AppLogo, JUMAN_LOGO_SRC, type AppLogoProps } from './app-logo'
export { CompanySwitcher, type CompanySwitcherProps } from './company-switcher'
export { NotificationButton, type NotificationButtonProps } from './notification-button'
export { BreadcrumbHost, type BreadcrumbHostProps } from './breadcrumb-host'
export { GlobalSearchButton, type GlobalSearchButtonProps } from './global-search-button'
export { CommandPaletteButton, type CommandPaletteButtonProps } from './command-palette-button'
export { DEFAULT_SHELL_SECTIONS } from './nav-config'
export type { ShellNavItem, ShellNavSection, ShellNavBadge } from './types'
