/** Whitelisted IPC channel names. */
export const IpcChannels = {
  API_INVOKE: 'juman:api:invoke',
  AUTH_GET_SESSION: 'juman:auth:getSession',
  AUTH_LOGIN: 'juman:auth:login',
  AUTH_CHANGE_PASSWORD: 'juman:auth:changePassword',
  AUTH_REFRESH: 'juman:auth:refresh',
  AUTH_LOGOUT: 'juman:auth:logout',
  AUTH_LOGOUT_ALL: 'juman:auth:logoutAll',
  AUTH_IS_AUTHENTICATED: 'juman:auth:isAuthenticated',
  AUTH_CHANGED: 'juman:auth:changed',
  SYSTEM_HEALTH: 'juman:system:health',
  SYSTEM_VERSION: 'juman:system:version',
  APP_GET_CONFIG: 'juman:app:getConfig',
  APP_GET_VERSION: 'juman:app:getVersion',
  APP_FIRST_RUN_STATE: 'juman:app:firstRun:state',
  APP_FIRST_RUN_COMPLETE: 'juman:app:firstRun:complete',
  APP_UPDATES_CHECK: 'juman:app:updates:check',
  DESKTOP_DIALOG_MESSAGE: 'juman:desktop:dialog:message',
  DESKTOP_WINDOW_MINIMIZE: 'juman:desktop:window:minimize',
  DESKTOP_WINDOW_MAXIMIZE: 'juman:desktop:window:maximize',
  DESKTOP_WINDOW_CLOSE: 'juman:desktop:window:close',
  DESKTOP_WINDOW_IS_MAXIMIZED: 'juman:desktop:window:isMaximized',
  DESKTOP_WINDOW_SET_TITLE: 'juman:desktop:window:setTitle',
  DESKTOP_FS_STUB: 'juman:desktop:fs:stub',
  HARDWARE_GET_CONFIG: 'juman:hardware:config:get',
  HARDWARE_SET_CONFIG: 'juman:hardware:config:set',
  HARDWARE_PRINTERS_LIST: 'juman:hardware:printers:list',
  HARDWARE_RECEIPT_TEST: 'juman:hardware:receipt:test',
  HARDWARE_LABEL_PREVIEW: 'juman:hardware:label:preview',
  HARDWARE_LABEL_PRINT: 'juman:hardware:label:print',
  HARDWARE_DRAWER_OPEN: 'juman:hardware:drawer:open',
  HARDWARE_CAMERA_CAPABILITIES: 'juman:hardware:camera:capabilities',
  HARDWARE_SCAN_EVENT: 'juman:hardware:scan:event',
  HARDWARE_BACKEND_STATUS: 'juman:hardware:backend:status',
  HARDWARE_BACKEND_START: 'juman:hardware:backend:start',
  HARDWARE_BACKEND_STOP: 'juman:hardware:backend:stop',
  HARDWARE_BACKEND_RESTART: 'juman:hardware:backend:restart',
  HARDWARE_BACKEND_REPAIR: 'juman:hardware:backend:repair',
  HARDWARE_OPEN_LOGS: 'juman:hardware:logs:open',
  HARDWARE_PRINTER_PROBE: 'juman:hardware:printers:probe',
  HARDWARE_DIAGNOSTICS: 'juman:hardware:diagnostics',
  APP_READ_ENV: 'juman:app:env:read',
  APP_PATCH_ENV: 'juman:app:env:patch',
  DIAGNOSTICS_RUN: 'juman:diagnostics:run',
  DIAGNOSTICS_GET_LAST: 'juman:diagnostics:getLast',
  DIAGNOSTICS_LOGS: 'juman:diagnostics:logs',
  DIAGNOSTICS_REPAIR: 'juman:diagnostics:repair',
  DIAGNOSTICS_EXPORT_REPORT: 'juman:diagnostics:exportReport',
  DIAGNOSTICS_OPEN_WINDOW: 'juman:diagnostics:openWindow',
  DIAGNOSTICS_PING: 'juman:diagnostics:ping'
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
