export const IpcChannels = {
  AUTH_GET_SESSION: 'auth:getSession',
  AUTH_LOGIN: 'auth:login',
  AUTH_LOGOUT: 'auth:logout',
  AUTH_CHANGED: 'auth:changed',
  AUTH_CHANGE_PASSWORD: 'auth:changePassword',
  API_INVOKE: 'api:invoke',
  MEDIA_UPLOAD: 'media:upload',
  RECEIPT_PRINT: 'receipt:print',
  REPORTS_EXPORT: 'reports:export',
  APP_GET_CONFIG: 'app:getConfig',
  APP_QUIT: 'app:quit',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
  STARTUP_GET_STATUS: 'startup:getStatus',
  STARTUP_CHANGED: 'startup:changed',
  STARTUP_RETRY: 'startup:retry',
} as const
