import {
  BARCODE_DEFAULT_PADDING,
  BARCODE_DEFAULT_PREFIX,
  BARCODE_DEFAULT_SEPARATOR,
  DEFAULT_CURRENCY_CODE,
  DEFAULT_CURRENCY_SYMBOL,
  DEFAULT_LOCALE,
  DEFAULT_TIMEZONE,
  SETTING_VALUE_TYPE,
} from '../shared/constants/business.constants';
export interface SettingSeed {
  readonly key: string;
  readonly value: string;
  readonly valueType: string;
  readonly category: string;
  readonly description: string;
  readonly isEditable: boolean;
}

export const DEFAULT_APP_SETTINGS: readonly SettingSeed[] = [
  { key: 'inventory.item.prefix', value: 'ITM', valueType: SETTING_VALUE_TYPE.STRING, category: 'catalog', description: 'Inventory item internal-code prefix', isEditable: true },
  { key: 'inventory.item.separator', value: '-', valueType: SETTING_VALUE_TYPE.STRING, category: 'catalog', description: 'Inventory item internal-code separator', isEditable: true },
  { key: 'inventory.item.padding', value: '8', valueType: SETTING_VALUE_TYPE.INTEGER, category: 'catalog', description: 'Inventory item internal-code zero-pad width', isEditable: true },

  {
    key: 'company.name',
    value: 'جمان',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'company',
    description: 'Company display name',
    isEditable: true,
  },
  {
    key: 'currency.code',
    value: DEFAULT_CURRENCY_CODE,
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'financial',
    description: 'ISO currency code',
    isEditable: false,
  },
  {
    key: 'currency.symbol',
    value: DEFAULT_CURRENCY_SYMBOL,
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'financial',
    description: 'Currency symbol',
    isEditable: true,
  },
  {
    key: 'locale.default',
    value: DEFAULT_LOCALE,
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'system',
    description: 'Default UI locale',
    isEditable: true,
  },
  {
    key: 'timezone.default',
    value: DEFAULT_TIMEZONE,
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'system',
    description: 'Business timezone',
    isEditable: true,
  },
  {
    key: 'barcode.prefix',
    value: BARCODE_DEFAULT_PREFIX,
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'inventory',
    description: 'Default barcode prefix',
    isEditable: true,
  },
  {
    key: 'barcode.separator',
    value: BARCODE_DEFAULT_SEPARATOR,
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'inventory',
    description: 'Barcode separator between prefix and sequence',
    isEditable: true,
  },
  {
    key: 'barcode.default_type',
    value: 'code128',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'inventory',
    description: 'Default barcode symbology',
    isEditable: true,
  },
  {
    key: 'barcode.padding',
    value: String(BARCODE_DEFAULT_PADDING),
    valueType: SETTING_VALUE_TYPE.INTEGER,
    category: 'inventory',
    description: 'Zero-pad width for barcode sequence',
    isEditable: true,
  },
  {
    key: 'media.max_upload_bytes',
    value: String(10 * 1024 * 1024),
    valueType: SETTING_VALUE_TYPE.INTEGER,
    category: 'media',
    description: 'Max upload size in bytes',
    isEditable: true,
  },
  {
    key: 'media.allowed_extensions',
    value: JSON.stringify(['jpg','jpeg','png','gif','webp','bmp','pdf','docx','xlsx','txt','csv']),
    valueType: SETTING_VALUE_TYPE.JSON,
    category: 'media',
    description: 'Allowed upload extensions',
    isEditable: true,
  },
  {
    key: 'media.allowed_mime_types',
    value: JSON.stringify([
      'image/jpeg','image/png','image/gif','image/webp','image/bmp',
      'application/pdf',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/zip','text/plain','text/csv','application/csv'
    ]),
    valueType: SETTING_VALUE_TYPE.JSON,
    category: 'media',
    description: 'Allowed upload MIME types',
    isEditable: true,
  },
  {
    key: 'customers.number.prefix',
    value: 'CUS',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'customers',
    description: 'Customer number prefix',
    isEditable: true,
  },
  {
    key: 'customers.number.separator',
    value: '-',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'customers',
    description: 'Customer number separator',
    isEditable: true,
  },
  {
    key: 'customers.number.padding',
    value: '8',
    valueType: SETTING_VALUE_TYPE.INTEGER,
    category: 'customers',
    description: 'Customer number zero-pad width',
    isEditable: true,
  },
  {
    key: 'rentals.number.prefix',
    value: 'RENT',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'rentals',
    description: 'Rental number prefix',
    isEditable: true,
  },
  {
    key: 'rentals.number.separator',
    value: '-',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'rentals',
    description: 'Rental number separator',
    isEditable: true,
  },
  {
    key: 'rentals.number.padding',
    value: '8',
    valueType: SETTING_VALUE_TYPE.INTEGER,
    category: 'rentals',
    description: 'Rental number zero-pad width',
    isEditable: true,
  },
  {
    key: 'sales.number.prefix',
    value: 'SALE',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'sales',
    description: 'Sale number prefix',
    isEditable: true,
  },
  {
    key: 'sales.number.separator',
    value: '-',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'sales',
    description: 'Sale number separator',
    isEditable: true,
  },
  {
    key: 'sales.number.padding',
    value: '8',
    valueType: SETTING_VALUE_TYPE.INTEGER,
    category: 'sales',
    description: 'Sale number zero-pad width',
    isEditable: true,
  },
  {
    key: 'reservations.number.prefix',
    value: 'RSV',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'reservations',
    description: 'Reservation number prefix',
    isEditable: true,
  },
  {
    key: 'reservations.number.separator',
    value: '-',
    valueType: SETTING_VALUE_TYPE.STRING,
    category: 'reservations',
    description: 'Reservation number separator',
    isEditable: true,
  },
  {
    key: 'reservations.number.padding',
    value: '8',
    valueType: SETTING_VALUE_TYPE.INTEGER,
    category: 'reservations',
    description: 'Reservation number zero-pad width',
    isEditable: true,
  },
];